name: halfadozen
favicon: null
layout_spectrum: 0.74582
typography_spectrum: 0.6531846518628299
title: Halfadozen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.13979219505563378
  lightness: 0.517088663764298
  saturation: 0.8932246067561209
  rhythmicContrast: 0.8807184975594282
purpose: []
